#Uncomment as needed
baseurl = "https://www.scifiideas.com"
languageCode = "en-us"
Title = "Scifi ideas generators"
# Copyright notice. This is displayer in the footer.
copyright = "&copy; Copyright notice"
theme = "potato-dark"


[params]

  # Google Analytics API key.
  ga_api_key = "UA-26882192-1"
  # Logo image. This is displayed ogp image.
  logo = "/path/to/logo"
  favicon = "/path/to/favicon"

[[menu.main]]
    name = "Spaceship name generator"
    url = "/spaceship-name-generator"
    weight = 1

[[menu.main]]
    name = "Alien species name generator"
    url = "/alien-species-name-generator"
    weight = 2

[related]
  # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
  threshold = 80

  # To get stable "See also" sections we, by default, exclude newer related pages.
  includeNewer = false

  # Will lower case keywords in both queries and in the indexes.
  toLower = false

  [[related.indices]]
  name = "keywords"
  weight = 150
  [[related.indices]]
  name  = "author"
  toLower = true
  weight = 30
  [[related.indices]]
  name  = "tags"
  weight = 100
  [[related.indices]]
  name  = "date"
  weight = 10
  pattern = "2017"


