#Uncomment as needed
baseurl = "https://www.scifiideas.com"
languageCode = "en-us"
Title = "Scifi ideas generators"
# Copyright notice. This is displayer in the footer.
copyright = "&copy; Copyright notice"
theme = "potato-dark"


[params]

  # Google Analytics API key.
  ga_api_key = "UA-26882192-1"
  # Logo image. This is displayed ogp image.
  logo = "/images/og-image.png"
  favicon = "/favicon"

[[menu.footer]]
    name = "Spaceship name generator"
    url = "/spaceship-name-generator"
    weight = 1

[[menu.footer]]
    name = "Alien species generator"
    url = "/alien-species-generator"
    weight = 2

[[menu.footer]]
    name = "Planet name generator"
    url = "/planet-name-generator"
    weight = 2

[[menu.footer]]
    name = "Sci-fi character name generator"
    url = "/sci-fi-character-name-generator"
    weight = 2

[[menu.footer]]
    name = "Technobabble generator"
    url = "/technobabble-generator"
    weight = 2

[[menu.footer]]
    name = "Random story idea generator"
    url = "/story-idea-generator"
    weight = 2

[[menu.footer]]
    name = "Future food generator"
    url = "/futuristic-food-generator"
    weight = 2

[[menu.footer]]
    name = "Cyberpunk name generator"
    url = "/cyberpunk-name-generator"
    weight = 2

[[menu.footer]]
    name = "Alien creature generator"
    url = "/alien-creature-generator"
    weight = 2

[[menu.footer]]
    name = "Star system name generator"
    url = "/star-system-name-generator"
    weight = 2

[[menu.footer]]
    name = "Random scenario generator"
    url = "/random-scenario-generator"
    weight = 2

[[menu.main]]
    name = "Spaceship name generator"
    url = "/spaceship-name-generator"
    weight = 1

[[menu.main]]
    name = "Alien species generator"
    url = "/alien-species-generator"
    weight = 2

[[menu.main]]
    name = "Planet name generator"
    url = "/planet-name-generator"
    weight = 2

[[menu.main]]
    name = "Scifi corporation name generator"
    url = "/scifi-company-name-generator"
    weight = 2

[related]
  # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
  threshold = 80

  # To get stable "See also" sections we, by default, exclude newer related pages.
  includeNewer = false

  # Will lower case keywords in both queries and in the indexes.
  toLower = false

  [[related.indices]]
  name = "keywords"
  weight = 150
  [[related.indices]]
  name  = "author"
  toLower = true
  weight = 30
  [[related.indices]]
  name  = "tags"
  weight = 100
  [[related.indices]]
  name  = "date"
  weight = 10
  pattern = "2017"

[markup.goldmark.renderer]
    unsafe= true
