[context.production.environment]
  HUGO_VERSION = "0.71.0"


[[redirects]]
from = "/spaceships"
to = "/spaceship-name-generator"
status = 301

[[redirects]]
from = "/spaceship-generator"
to = "/spaceship-name-generator"
status = 301

[[redirects]]
from = "/spaceships-generator"
to = "/spaceship-name-generator"
status = 301

[[redirects]]
from = "/home"
to = "/spaceship-name-generator"
status = 301

[[redirects]]
from = "/aliens"
to = "/alien-species-name-generator"
status = 301