[context.production.environment]
  HUGO_VERSION = "0.71.0"


[[redirects]]
from = "/spaceships"
to = "/spaceship-name-generator"
status = 301

[[redirects]]
from = "/spaceship-generator"
to = "/spaceship-name-generator"
status = 301

[[redirects]]
from = "/spaceships-generator"
to = "/spaceship-name-generator"
status = 301

[[redirects]]
from = "/home"
to = "/spaceship-name-generator"
status = 301

[[redirects]]
from = "/planet-generator/"
to = "/planet-name-generator"
status = 301

[[redirects]]
from = "/aliens"
to = "/alien-species-name-generator"
status = 301

[[redirects]]
from = "/category/sfi/alien-ideas/alien-profiles/"
to = "/alien-species-generator"
status = 301

[[redirects]]
from = "/sfi/story-ideas/car-hackers-automated-car-revolution/"
to = "/posts/car-hackers-automated-car-revolution/"
status = 301

[[redirects]]
from = "/sfi/story-ideas/story-idea-control-planet-13"
to = "/posts/car-hackers-automated-car-revolution/"
status = 301

[[redirects]]
from = "/writing-2/writing-advice/a-guide-to-science-fiction-subgenres/"
to = "/posts/a-guide-to-science-fiction-subgenres/"
status = 301

[[redirects]]
from = "/sfi/story-ideas/10-ideas-for-a-time-travel-story/"
to = "/posts/10-ideas-for-a-time-travel-story/"
status = 301

[[redirects]]
from = "/writing-2/writing-advice/25-different-science-fiction-settings/"
to = "/posts/25-different-science-fiction-settings/"
status = 301

[[redirects]]
from = "/sfi/x-ifs-alternate-history-scenarios/"
to = "/posts/50-ideas-for-alternate-history-scenarios/"
status = 301

[[redirects]]
from = "/science-2/sciency-words-the-gaia-principle/"
to = "/posts/sciency-words-the-gaia-principle/"
status = 301

[[redirects]]
from = "/category/sfi/story-ideas/"
to = "/posts/25-different-science-fiction-settings/"
status = 301

[[redirects]]
from = "/science-2/life-evolve-inside-gas-giant/"
to = "/posts/life-evolve-inside-gas-giant/"
status = 301

[[redirects]]
from = "/writing-2/solarpunk-we-are-golden-and-our-future-is-bright/"
to = "/posts/solarpunk-we-are-golden-and-our-future-is-bright/"
status = 301

